import type { Metadata } from 'next'
import localFont from 'next/font/local'
import Link from 'next/link'
import './globals.css'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900'
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
  analytics,
  team
}: {
  children: React.ReactNode
  analytics: React.ReactNode
  team: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-gray-800 p-4">
          <ul className="flex space-x-4">
            <li>
              <Link
                href="/"
                className="text-white hover:text-gray-300"
              >
                首页
              </Link>
            </li>
            <li>
              <Link
                href="/aaa"
                className="text-white hover:text-gray-300"
              >
                AAA
              </Link>
            </li>
            <li>
              <Link
                href="/bbb"
                className="text-white hover:text-gray-300"
              >
                BBB
              </Link>
            </li>
          </ul>
        </nav>
        {children}
        {analytics}
        {team}
      </body>
    </html>
  )
}
